name: pytests

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release
      - develop

jobs:
  run-tests:

    runs-on: ubuntu-latest
    environment: sanya_tests

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Show information
      run: | 
        echo "ФИО: ${{ vars.NAME}}, Номер группы: ${{ vars.GROUP }}, GitHub User: ${{ github.actor }}"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run tests
      run: |
        python -m unittest discover -s all_tests -v

    - name: Check code style
      run: flake8 .
    - run: echo "This job's status is ${{ job.status }}."
